CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "description" int,
  "level" int,
  "teacher" int,
  "video" int
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar,
  "password" varchar,
  "age" int,
  "role_id" int NOT NULL

);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(40),
  "url" varchar
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(40)
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(20)
);

CREATE TABLE "videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_id" int
);

CREATE TABLE "user_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int NOT NULL,
  "user_id" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("description") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level") REFERENCES "levels" ("id");

ALTER TABLE "user_courses" ADD FOREIGN KEY ("course_id") REFERENCES "users" ("id");

ALTER TABLE "user_courses" ADD FOREIGN KEY ("user_id") REFERENCES "courses" ("id");

ALTER TABLE "videos" ADD FOREIGN KEY ("title_id") REFERENCES "course_videos" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("video") REFERENCES "videos" ("id");


INSERT INTO roles (name) VALUES ('student'); 

INSERT INTO roles (name) VALUES ('teacher');

INSERT INTO roles (name) VALUES ('admin');

INSERT INTO categories (name) VALUES ('backend');

INSERT INTO categories (name) VALUES ('frontend');

INSERT INTO levels (level) VALUES ('beginner');   

INSERT INTO levels (level) VALUES ('middle');

INSERT INTO levels (level) VALUES ('advanced');        

INSERT INTO course_videos (title, url) VALUES ('video1', 'url1');   

INSERT INTO course_videos (title, url) VALUES ('video2', 'url2');

INSERT INTO course_videos (title, url) VALUES ('video3', 'url3');

INSERT INTO users (name, email, password, age, role_id) VALUES ('Ian', 'email1', 'abcd1', 32, 2);
INSERT INTO users (name, email, password, age, role_id) VALUES ('Joseph', 'email2', 'abcd2', 16, 1);
INSERT INTO users (name, email, password, age, role_id) VALUES ('Mike', 'email3', 'abcd3', 28, 1);
INSERT INTO users (name, email, password, age, role_id) VALUES ('Louis', 'email4', 'abcd4', 25, 3);

INSERT INTO videos (title_id) VALUES (1);

INSERT INTO videos (title_id) VALUES (2);

INSERT INTO videos (title_id) VALUES (3);

INSERT INTO courses (title, description, level, teacher, video) VALUES ('NodeJS', 1, 2, 1, 1);

INSERT INTO courses (title, description, level, teacher, video) VALUES ('ReactJS', 1, 3, 1, 2);

INSERT INTO courses (title, description, level, teacher, video) VALUES ('SASS', 2, 2, 1, 3);

INSERT INTO user_courses (course_id, user_id) VALUES (1, 1);

INSERT INTO user_courses (course_id, user_id) VALUES (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3);

ALTER TABLE users ADD COLUMN course int;

ALTER TABLE "users" ADD FOREIGN KEY ("course") REFERENCES "user_courses" ("id") ;

UPDATE users set course=1 WHERE id=1;

UPDATE users set course=3 WHERE id=2;

UPDATE users set course=2 WHERE id=3;

 SELECT users.id, users.name, users.email,users.password, users.age, users.role_id, courses.title, courses.description, courses,level, roles.name, videos.title_id, categories.name  FROM users JOIN user_courses ON users.course=user_courses.id JOIN courses ON user_courses.course_id=courses.id JOIN roles ON users.role_id=roles.id JOIN videos ON courses.video=videos.title_id JOIN categories ON courses.description=categories.id;